baseurl         = "https://elegant-neumann-74d908.netlify.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Phil Lembo"
  subtitle    = "Just another tech"

  cover       = "uploads/header.jpg"
  description = "A site static site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "philinnc"
  # fbName = ""
  githubName = "plembo"
  linkedinName = "phil-lembo-nc"

  logo = ""
  orgName = "Phil Lembo"
  orgWebsite = "https://www.casalembo.com"
  orgDescription = "A private home"

  author = "Phil Lembo"
  authorAvatar = "uploads/profile_picture.jpg"
  authorLocation = "Raleigh, NC"
  authorWebsite = "https://plembo.github.io"
  authorDescription = "Enterprise Architect"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Projects"
  url = "/tags/project/"
  weight = 100

[[menu.main]]
  name = "My Life"
  url = "/categories/life/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95
